# Generated by Django 5.0.1 on 2024-02-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renty', '0006_property_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_details',
            old_name='ID',
            new_name='id_type',
        ),
    ]
