# Generated by Django 5.0.1 on 2024-02-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renty', '0007_rename_id_property_details_id_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_Details',
        ),
    ]
