# Generated by Django 5.0.1 on 2024-02-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renty', '0013_alter_property_details_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_details',
            old_name='ward_no',
            new_name='price',
        ),
    ]
