# Generated by Django 5.0.1 on 2024-02-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renty', '0018_alter_property_details_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_Details',
        ),
    ]
