# Generated by Django 5.0.1 on 2024-02-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renty', '0019_delete_property_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mob_number', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=100)),
                ('id_num', models.CharField(max_length=100)),
                ('issue_auth', models.CharField(max_length=100)),
                ('issue_state', models.CharField(max_length=100)),
                ('issue_date', models.DateField(max_length=100)),
                ('exp_date', models.DateField(max_length=100)),
                ('add_type', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('block_no', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('prop_type', models.CharField(max_length=100)),
                ('bedroom_no', models.CharField(max_length=100)),
                ('floors', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('tenant_type', models.CharField(max_length=100)),
                ('prop_img', models.ImageField(blank=True, null=True, upload_to='property')),
            ],
        ),
    ]
