# Generated by Django 5.0.1 on 2024-02-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renty', '0020_property_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_details',
            name='add_type',
        ),
        migrations.RemoveField(
            model_name='property_details',
            name='block_no',
        ),
        migrations.RemoveField(
            model_name='property_details',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property_details',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='property_details',
            name='state',
        ),
    ]
