# Generated by Django 5.0.1 on 2024-02-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renty', '0021_remove_property_details_add_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_details',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
